#include <RISMD.h>
#include <lcdt___logicals.standard.util.schedule.program_handle.h>

static char const lcmd_type_name_LOGICALSx2ESTANDARDx2EUTILx2ESCHEDULEx2EPROGRAM_HANDLE[] RISMD_ATTRIBUTES = "LOGICALS.STANDARD.UTIL.SCHEDULE.PROGRAM_HANDLE";
extern RISMDSimpleNumType const risMdType_INT;
RISMDDerivedType const lcmd_type_LOGICALSx2ESTANDARDx2EUTILx2ESCHEDULEx2EPROGRAM_HANDLE RISMD_ATTRIBUTES = INIT_RISMDDerivedType(lcmd_type_name_LOGICALSx2ESTANDARDx2EUTILx2ESCHEDULEx2EPROGRAM_HANDLE, &risMdType_INT);
