#include <RISMD.h>
#include <lcdt___logicals.system.network.tcp.tcp_clienthandle.h>

static char const lcmd_type_name_LOGICALSx2ESYSTEMx2ENETWORKx2ETCPx2ETCP_CLIENTHANDLE[] RISMD_ATTRIBUTES = "LOGICALS.SYSTEM.NETWORK.TCP.TCP_CLIENTHANDLE";
extern RISMDSimpleNumType const risMdType_DWORD;
RISMDDerivedType const lcmd_type_LOGICALSx2ESYSTEMx2ENETWORKx2ETCPx2ETCP_CLIENTHANDLE RISMD_ATTRIBUTES = INIT_RISMDDerivedType(lcmd_type_name_LOGICALSx2ESYSTEMx2ENETWORKx2ETCPx2ETCP_CLIENTHANDLE, &risMdType_DWORD);
