#ifndef LC_PROT_LCDT___LOGICALSx2ESYSTEMx2ENETWORKx2ETCPx2ETCP_SERVERHANDLE__H
#define LC_PROT_LCDT___LOGICALSx2ESYSTEMx2ENETWORKx2ETCPx2ETCP_SERVERHANDLE__H

#include <LC3CGBase.h>

/*                            Typedefs                         */
typedef LC_TD_DWORD LC_TD_DataType_LOGICALSx2ESYSTEMx2ENETWORKx2ETCPx2ETCP_SERVERHANDLE;

/*                   ColdBoot Initialization Macro             */
#define LC_INIT_DataType_LOGICALSx2ESYSTEMx2ENETWORKx2ETCPx2ETCP_SERVERHANDLE(p) \
{ \
  LC_INIT_DWORD(p); \
}

/*                   WarmBoot Initialization Macro             */
#define LC_WINIT_DataType_LOGICALSx2ESYSTEMx2ENETWORKx2ETCPx2ETCP_SERVERHANDLE(p,RF) \
{ \
  LC_WINIT_DWORD(p,RF); \
}

/*                ColdBoot Initialization Macro for Arrays            */
#define LC_INIT_ARRAY_OF_DataType_LOGICALSx2ESYSTEMx2ENETWORKx2ETCPx2ETCP_SERVERHANDLE(p,ARRAYSIZE) \
{ \
  LC_TD_DataType_LOGICALSx2ESYSTEMx2ENETWORKx2ETCPx2ETCP_SERVERHANDLE * ptrToElement_ArrayOf_LOGICALSx2ESYSTEMx2ENETWORKx2ETCPx2ETCP_SERVERHANDLE = (LC_TD_DataType_LOGICALSx2ESYSTEMx2ENETWORKx2ETCPx2ETCP_SERVERHANDLE*)(p);\
  LC_TD_DataType_LOGICALSx2ESYSTEMx2ENETWORKx2ETCPx2ETCP_SERVERHANDLE * arrayEnd = ptrToElement_ArrayOf_LOGICALSx2ESYSTEMx2ENETWORKx2ETCPx2ETCP_SERVERHANDLE+ARRAYSIZE;\
  for (; ptrToElement_ArrayOf_LOGICALSx2ESYSTEMx2ENETWORKx2ETCPx2ETCP_SERVERHANDLE < arrayEnd; ptrToElement_ArrayOf_LOGICALSx2ESYSTEMx2ENETWORKx2ETCPx2ETCP_SERVERHANDLE++) \
  { \
    LC_INIT_DataType_LOGICALSx2ESYSTEMx2ENETWORKx2ETCPx2ETCP_SERVERHANDLE(ptrToElement_ArrayOf_LOGICALSx2ESYSTEMx2ENETWORKx2ETCPx2ETCP_SERVERHANDLE); \
  } \
}

/*                WarmBoot Initialization Macro for Arrays            */
#define LC_WINIT_ARRAY_OF_DataType_LOGICALSx2ESYSTEMx2ENETWORKx2ETCPx2ETCP_SERVERHANDLE(p,ARRAYSIZE,RF) \
{ \
  if (RF==0) \
  { \
    LC_INIT_ARRAY_OF_DataType_LOGICALSx2ESYSTEMx2ENETWORKx2ETCPx2ETCP_SERVERHANDLE(p,ARRAYSIZE); \
  } \
}

#endif
